services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 4000:80
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 4040:3000
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
