services:
  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - 4000:80
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - 4040:3000
    depends_on:
      - mongo_db

  mongo_db:
    container_name: mongo_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
